# © 2016 Synopsys, Inc.  All rights reserved.             
#                                                                  
# This script is proprietary and confidential information of        
# Synopsys, Inc. and may be used and disclosed only as authorized   
# per your agreement with Synopsys, Inc. controlling such use and   
# disclosure.                                                       
#   
#   Article Number
#   000031065

proc report_error_data_objects {args} {
    parse_proc_arguments -args $args val
    set unique_err [lsort -unique [get_attribute [get_drc_errors -error_data $val(-error_data)] type_name]]
    set i 1
    set z 40
    foreach err_type $unique_err {
        echo "\n$i. Error objects with \"$err_type\" violations :-"
        echo [string repeat = [expr [string length $err_type] + $z]]
        sh rm -rf err_obj_file
        set all_err_objects [get_attribute [get_drc_errors -error_data $val(-error_data) -filter type_name=="$err_type"] objects]
        foreach err_object $all_err_objects {
            echo [get_object_name $err_object] >> err_obj_file
        }
        exec sort -u err_obj_file > sorted_err_obj_file
        set files sorted_err_obj_file
        set j 1
        foreach file $files {
            set fp [open $file]
            while {[gets $fp line] >= 0} {
                puts "$j) $line"
                incr j
            }
            close $fp
        }
        incr i
    }
}
define_proc_attributes report_error_data_objects -info "Script to categorize unique error objects from the error data generated by check_routes or check_lvs." \
    -define_args {
        { -error_data "Specify the error data generated by check_routes or check_lvs" error_data_name string required}
    }
